API
mishanya1111/MGrebenkinAngular pull request #12
Opened 2024-07-11 15:19 UTC by mishanya1111

Хотел сделать как в задании но, нет покемонов которые имеют и огонь и воду, поэтому сделал или огонь или воду

2024-07-12 11:12 UTC, msilina-ibagroup-eu requested changes
дейстивельно, с Fire и Water нет. Пусть будет Water и Poison

2024-07-12 11:12 UTC, msilina-ibagroup-eu commented on script.js
> +        const result = dataJSON.filter((data) => {
а почему просто не проверить, что нужное условие выполняется? 
а ты переписываешь условие в filter, чтобы наоборот исключить ненужное
и тут же проверить, что в Types есть нужные тебе типы

2024-07-15 09:41 UTC, mishanya1111 commented on script.js
> +        const result = dataJSON.filter((data) => {
моя идея может показаться неправильной, но из большого набора данных, неправильных будет больше , поэтому , чтобы не делать лишние действия, я разбил проверку на 2 части

2024-07-16 10:33 UTC, msilina-ibagroup-eu commented on script.js
> +        const result = dataJSON.filter((data) => {
на ui, как правило не оперируют большими наборами данных. Если тебе backend возвращает 3 тыс записей, а тебе из них нужно всего 15, ты просишь создать отдельный запрос. 
даже, если мы говорим о выборке по условиям из 250 записей, это практически не скажется на производительности
ты назовешь свою функцию, например, getFilteredData() (потому что невозможно в названии вместить весь смысл, а комментарии почти никто не пишет), напишешь там неочевидные условия, понятные только тебе, и никто не сможет это суппортить. Ее просто перепишут

2024-07-16 10:39 UTC, msilina-ibagroup-eu requested changes

2024-07-16 10:39 UTC, msilina-ibagroup-eu commented on script.js
> +            data['Special Attack(s)'].map((attack) => attack?.Type).includes("Water") &&
у тебя в данных уже есть готовый массив с типами
![image](https://github.com/user-attachments/assets/2e3ab871-fbf2-4088-81e1-bcf3bd3ba450)

2024-07-16 10:56 UTC, mishanya1111 commented on script.js
> +            data['Special Attack(s)'].map((attack) => attack?.Type).includes("Water") &&
я переписал но там появился покемон который в специальной атаке не имеет яд

2024-07-18 12:29 UTC, msilina-ibagroup-eu approved these changes

2024-07-24 11:59 UTC, merged