calculateTotalPrice
mishanya1111/MGrebenkinAngular pull request #9
Opened 2024-07-01 10:10 UTC by mishanya1111

Можно сделать и в одну map, нот так понятнее

2024-07-03 08:38 UTC, msilina-ibagroup-eu requested changes

2024-07-03 08:38 UTC, msilina-ibagroup-eu commented on script.js
> +const calculateTotalPrice = function (items, baseCurrency, exchangeRates) {
или так
```
const calculateTotalPrice = (items, baseCurrency, exchangeRates) => { ... }
```
или так
```
function calculateTotalPrice(items, baseCurrency, exchangeRates) { ... }
```

2024-07-03 08:38 UTC, msilina-ibagroup-eu commented on script.js
> +    return items.map(({_, price, currency}) => [currency, price])
можно все сделать в одном reduce, например
```
purchases.reduce((acc, purchase) => {
  if (purchase.currency !== baseCurrency) {
    ...
  } else {
    ...
  }
}, 0);
```

2024-07-03 10:58 UTC, mishanya1111 commented on script.js
> +const calculateTotalPrice = function (items, baseCurrency, exchangeRates) {
Все вопросы к курсу, он так постоянно делает)) . Я предпочитаю 2

2024-07-04 20:51 UTC, msilina-ibagroup-eu approved these changes

2024-07-05 11:13 UTC, merged